version: '3'
services: 
  php:
    image: php
    build: ./docker/php
    volumes: 
      - ./app:/var/www
  web: 
    image: nginx:latest
    volumes: 
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
      - ./app:/var/www
    ports: 
      - "8000:80"
    depends_on:
      - php
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306